"""FixService — orchestrates AI, VCS, and worktree ports for implementing review fixes."""
import logging
import os
import time
from collections.abc import AsyncGenerator

from app.domain.exceptions import WorktreeNoChangesError, WorktreeNotFoundError
from app.ports.ai_provider import AIProvider, FixChunkEvent
from app.ports.vcs_port import VCSPort
from app.ports.worktree_port import WorktreePort

logger = logging.getLogger(__name__)

_DEFAULT_COMMIT_MSG_TEMPLATE = "fix: address review comment on PR #{pr_number}"
_MAX_DIFF_RESULT_CHARS = 10_000   # max diff chars sent in the streaming result event
_MAX_PROMPT_DIFF_CHARS = 6_000    # max diff chars embedded in AI prompts
_PR_FOOTER_TEMPLATE = "\n\n---\n<sub>Addresses review comment on #{pr_number}</sub>\n<sub>🤖 Generated by gh-review-tool</sub>"


class FixService:
    def __init__(
        self, ai: AIProvider, vcs: VCSPort, worktree: WorktreePort
    ) -> None:
        self._ai = ai
        self._vcs = vcs
        self._worktree = worktree

    async def stream_fix(
        self, repo_full_name: str, pr_number: int, comment_body: str
    ) -> AsyncGenerator[dict, None]:
        """Stream fix implementation. Yields status/chunk/result/error/done dicts."""
        try:
            yield {"type": "status", "text": "Fetching PR info..."}
            pr_branch = self._vcs.get_pr_head_branch(repo_full_name, pr_number)

            yield {"type": "status", "text": f"Preparing worktree for PR #{pr_number}..."}
            wt_path = self._worktree.create(repo_full_name, pr_number, pr_branch)
            yield {"type": "status", "text": f"Worktree ready at {wt_path}"}

            yield {"type": "status", "text": "Running AI to implement fix..."}
            full_output: list[str] = []
            async for chunk in self._ai.stream_fix(wt_path, repo_full_name, pr_number, comment_body):
                full_output.append(chunk.text)
                yield {"type": "chunk", "text": chunk.text}

            if not self._worktree.has_changes(wt_path):
                yield {"type": "error", "text": "AI did not make any file changes."}
                yield {
                    "type": "result",
                    "worktree_path": wt_path,
                    "has_changes": False,
                    "diff": "",
                    "text": "".join(full_output).strip(),
                }
            else:
                self._worktree.stage_all(wt_path)
                diff_text = self._worktree.get_staged_diff(wt_path)
                yield {"type": "status", "text": f"Changes ready in {wt_path}"}
                yield {
                    "type": "result",
                    "worktree_path": wt_path,
                    "branch": pr_branch,
                    "has_changes": True,
                    "diff": diff_text[:_MAX_DIFF_RESULT_CHARS],
                    "text": "".join(full_output).strip(),
                }

            yield {"type": "done"}

        except Exception as e:
            logger.exception("Fix flow failed")
            yield {"type": "error", "text": str(e)}
            yield {"type": "done"}

    async def push_fix(
        self,
        repo_full_name: str,
        pr_number: int,
        diff: str,
        comment_body: str,
    ) -> dict:
        """Commit and push changes to the existing PR branch.

        Staging is the caller's responsibility — stream_fix already called stage_all.

        Raises:
            WorktreeNotFoundError: if the worktree directory does not exist.
            WorktreeNoChangesError: if there are no uncommitted changes.
        """
        wt_path = self._worktree.worktree_path(repo_full_name, pr_number)
        if not os.path.isdir(wt_path):
            raise WorktreeNotFoundError(f"Worktree not found for PR #{pr_number}. Run fix first.")
        if not self._worktree.has_changes(wt_path):
            raise WorktreeNoChangesError(f"No uncommitted changes in worktree for PR #{pr_number}.")
        commit_msg = await self._generate_commit_message(diff, comment_body, pr_number)
        self._worktree.commit_and_push(wt_path, commit_msg)
        return {"status": "pushed", "commit_message": commit_msg}

    async def create_pr_from_fix(
        self,
        repo_full_name: str,
        pr_number: int,
        pr_branch: str,
        diff: str,
        comment_body: str,
    ) -> dict:
        """Create a new branch + PR from the fix changes.

        Raises:
            WorktreeNotFoundError: if the worktree directory does not exist.
            WorktreeNoChangesError: if there are no uncommitted changes.
        """
        wt_path = self._worktree.worktree_path(repo_full_name, pr_number)
        if not os.path.isdir(wt_path):
            raise WorktreeNotFoundError(f"Worktree not found for PR #{pr_number}. Run fix first.")
        if not self._worktree.has_changes(wt_path):
            raise WorktreeNoChangesError(f"No uncommitted changes in worktree for PR #{pr_number}.")
        commit_msg = await self._generate_commit_message(diff, comment_body, pr_number)
        pr_title, pr_body = await self._generate_pr_description(
            pr_number, pr_branch, diff, comment_body
        )
        new_branch = f"fix/pr{pr_number}-review-{int(time.time())}"
        self._worktree.stage_all(wt_path)
        self._worktree.create_branch_and_push(wt_path, new_branch, commit_msg)
        pr_result = self._vcs.create_pr(repo_full_name, new_branch, pr_branch, pr_title, pr_body)
        return {
            "status": "created",
            "pr_url": pr_result["url"],
            "pr_title": pr_title,
            "commit_message": commit_msg,
            "branch": new_branch,
        }

    async def _generate_commit_message(
        self, diff: str, comment_body: str, pr_number: int
    ) -> str:
        prompt = (
            "Generate a concise git commit message (1 line subject, optional body) for the following changes. "
            "The changes address this review comment:\n\n"
            f"Review comment: {comment_body}\n\n"
            f"Diff:\n```\n{diff[:_MAX_PROMPT_DIFF_CHARS]}\n```\n\n"
            "Reply with ONLY the commit message, no explanation, no markdown fences."
        )
        try:
            return await self._ai.generate_text(prompt, timeout=60)
        except Exception:
            logger.warning("Failed to generate commit message with AI, using default")
            return _DEFAULT_COMMIT_MSG_TEMPLATE.format(pr_number=pr_number)

    async def _generate_pr_description(
        self,
        pr_number: int,
        pr_branch: str,
        diff: str,
        comment_body: str,
    ) -> tuple[str, str]:
        prompt = (
            "Generate a pull request title and body for the following fix. "
            "The fix addresses a review comment on an existing PR.\n\n"
            f"Original PR branch: {pr_branch}\n"
            f"Review comment: {comment_body}\n\n"
            f"Diff:\n```\n{diff[:_MAX_PROMPT_DIFF_CHARS]}\n```\n\n"
            "Reply in this exact format (no markdown fences around the whole thing):\n"
            "TITLE: <concise PR title>\n"
            "BODY:\n<markdown PR body with a Summary section and what was changed>"
        )
        try:
            text = await self._ai.generate_text(prompt, timeout=60)
            if "TITLE:" in text and "BODY:" in text:
                title = text.split("BODY:")[0].replace("TITLE:", "").strip()
                body = text.split("BODY:", 1)[1].strip()
                body += _PR_FOOTER_TEMPLATE.format(pr_number=pr_number)
                return title, body
            else:
                logger.warning("AI PR description response did not match expected TITLE/BODY format; using default")
        except Exception:
            logger.warning("Failed to generate PR description with AI, using default")

        default_title = f"fix: address review comment on #{pr_number}"
        default_body = (
            f"## Summary\n\nFixes review comment on PR #{pr_number}.\n\n"
            f"### Review comment\n> {comment_body[:500]}\n\n"
            f"---\n<sub>🤖 Generated by gh-review-tool</sub>"
        )
        return default_title, default_body
