import { writable, get } from 'svelte/store';
import type { PR, Review, Comment, CommentAnalysis } from '../lib/types';
import { api } from '../lib/api';
import { selectedModel } from './ui';

export const prs = writable<PR[]>([]);
export const activePR = writable<PR | null>(null);
export const activeTab = writable<'review' | 'comments'>('review');
export const cachedReview = writable<Review | null>(null);
export const comments = writable<Comment[]>([]);

// Findings the user has staged for a batched "Request Changes" review.
// Cleared when the active PR changes or a batch is published.
export const stagedReviewFindings = writable<import('../lib/types').Finding[]>([]);
export const publishReviewsModalOpen = writable<boolean>(false);

// Reset staging when the active PR changes — staging is per-PR.
activePR.subscribe(() => {
  stagedReviewFindings.set([]);
});

export function stageFinding(finding: import('../lib/types').Finding): boolean {
  let added = false;
  stagedReviewFindings.update((list) => {
    if (list.some((f) => f.title === finding.title && f.priority === finding.priority && f.file === finding.file && f.line === finding.line)) {
      return list;
    }
    added = true;
    return [...list, finding];
  });
  return added;
}

export function unstageFinding(finding: import('../lib/types').Finding): void {
  stagedReviewFindings.update((list) =>
    list.filter((f) => !(f.title === finding.title && f.priority === finding.priority && f.file === finding.file && f.line === finding.line))
  );
}

export async function loadPRs(owner: string, repo: string, forceRefresh = false): Promise<void> {
  if (forceRefresh) {
    const data = await api.post<PR[]>(`/prs/${owner}/${repo}/refresh`);
    prs.set(data);
  } else {
    const data = await api.get<PR[]>(`/prs/${owner}/${repo}`);
    prs.set(data);
  }
}


export async function loadComments(owner: string, repo: string, prNumber: number): Promise<void> {
  const data = await api.get<RawPRDetail>(`/pr/${owner}/${repo}/${prNumber}`);
  const raw: RawComment[] = [
    ...(data.comments ?? []),
    ...(data.reviews ?? []).filter((r) => r.body),
    ...(data.review_comments ?? []),
  ];
  comments.set(raw.map((c, i) => normalizeComment(c, i)));
}

export async function analyzeComments(owner: string, repo: string, prNumber: number, signal?: AbortSignal): Promise<void> {
  const data = await api.post<{ comments: RawComment[]; analysis: RawAnalysis[] }>(
    `/comments/${owner}/${repo}/${prNumber}/analyze`,
    undefined,
    signal,
  );
  const authorStr = (author: string | { login: string }) => typeof author === 'string' ? author : author.login;
  const analysisMap = new Map(data.analysis.map((a) => [a.author, a]));
  comments.set(
    data.comments.map((c, i) => {
      const raw = normalizeComment(c, i);
      const analysis = analysisMap.get(authorStr(c.author));
      if (analysis) {
        raw.analysis = {
          valid: analysis.valid,
          interest: analysis.interest as CommentAnalysis['interest'],
          critical: analysis.criticality === 'P0',
          priority: analysis.criticality as CommentAnalysis['priority'],
        };
      }
      return raw;
    })
  );
}

function _formatFindingBody(finding: import('../lib/types').Finding, withFooter = true): string {
  const model = get(selectedModel);
  const footer = withFooter
    ? `\n\n---\n*Generated by gh-review-tool${model ? ` using \`${model}\`` : ''}*`
    : '';
  const main = finding.suggestion
    ? `**${finding.priority}: ${finding.title}**\n\n${finding.description}\n\n**Suggestion:**\n${finding.suggestion}`
    : `**${finding.priority}: ${finding.title}**\n\n${finding.description}`;
  return main + footer;
}

export async function publishFinding(
  owner: string,
  repo: string,
  prNumber: number,
  finding: import('../lib/types').Finding
): Promise<void> {
  const fullRepo = `${owner}/${repo}`;
  const body = _formatFindingBody(finding);

  // P1 findings escalate to a single-finding REQUEST_CHANGES review so the PR
  // shows a "Changes requested" banner instead of a casual comment.
  if (finding.priority === 'P1') {
    const reviewBody = `Requesting changes: ${finding.title}`;
    const inlineComments = finding.file && finding.line != null
      ? [{ path: finding.file, line: finding.line, body }]
      : [];
    await api.post('/review/publish', {
      repo: fullRepo,
      pr_number: prNumber,
      body: inlineComments.length > 0 ? reviewBody : body,
      event: 'REQUEST_CHANGES',
      comments: inlineComments,
    });
    return;
  }

  if (finding.file && finding.line != null) {
    await api.post('/comment/inline', {
      repo: fullRepo,
      pr_number: prNumber,
      body,
      path: finding.file,
      line: finding.line,
    });
  } else {
    await api.post('/comment/publish', {
      repo: fullRepo,
      pr_number: prNumber,
      body,
    });
  }
}

export async function publishStagedReview(
  owner: string,
  repo: string,
  prNumber: number,
  reviewBody: string
): Promise<void> {
  const fullRepo = `${owner}/${repo}`;
  const staged = get(stagedReviewFindings);
  if (staged.length === 0) {
    throw new Error('No findings staged for review');
  }

  // Findings with file+line become inline comments. Findings without file/line
  // are appended into the review body so they aren't lost.
  const inlineComments: { path: string; line: number; body: string }[] = [];
  const orphanLines: string[] = [];
  for (const finding of staged) {
    if (finding.file && finding.line != null) {
      inlineComments.push({
        path: finding.file,
        line: finding.line,
        body: _formatFindingBody(finding, false),
      });
    } else {
      orphanLines.push(`- **${finding.priority}**: ${finding.title}\n  ${finding.description}`);
    }
  }

  const model = get(selectedModel);
  const footer = `\n\n---\n*Generated by gh-review-tool${model ? ` using \`${model}\`` : ''}*`;
  let body = reviewBody.trim() || 'Review requested by gh-review-tool';
  if (orphanLines.length > 0) {
    body += `\n\n**Additional findings (no file/line):**\n${orphanLines.join('\n')}`;
  }
  body += footer;

  await api.post('/review/publish', {
    repo: fullRepo,
    pr_number: prNumber,
    body,
    event: 'REQUEST_CHANGES',
    comments: inlineComments,
  });
  stagedReviewFindings.set([]);
}

// ── Internal types for raw API responses ──

interface RawComment {
  id: number;
  author: string | { login: string };
  body: string;
  path?: string;
  line?: number;
  created_at: string;
  comment_type?: string;
}

interface RawAnalysis {
  author: string;
  criticality: string;
  valid: boolean;
  interest: string;
  summary: string;
  original_body: string;
}

interface RawPRDetail {
  comments?: RawComment[];
  reviews?: RawComment[];
  review_comments?: RawComment[];
}

function normalizeComment(c: RawComment, index: number): Comment {
  const authorStr = typeof c.author === 'string' ? c.author : c.author.login;
  return {
    id: c.id ?? index,
    author: authorStr,
    body: c.body,
    file: c.path,
    line: c.line,
    created_at: c.created_at,
    comment_type: c.comment_type ?? 'pr_comment',
  };
}

export async function deleteComment(
  repo: string,
  commentId: number,
  commentType: string
): Promise<void> {
  await api.delete('/comment', { repo, comment_id: commentId, comment_type: commentType });
}
